sudo: false

os:
  - linux

addons:
  apt:
    packages:
    - graphviz

language: c
compiler:
  - gcc
  - clang

before_install:
  - bison --version
  - flex --version

install:
  - ./get-deps.sh
  - ./get-extra-deps.sh
  - ./build-deps.sh
script:
  - make -e all
  - VERBOSE=1 make -e check

notifications:
  email: false