language: c

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
    - os: linux
      dist: bionic
      compiler: clang

addons:
  apt:
    packages:
    - graphviz

before_install:
  - bison --version
  - flex --version

install:
  - ./get-deps.sh
  - ./get-extra-deps.sh
  - ./build-deps.sh
script:
  - make -e all
  - VERBOSE=1 make -e check

notifications:
  email: false