---
# configuration for GitHub Actions
name: gr1c tests
on:
    push:
    pull_request:

jobs:
    build-and-test:
        name: Build and test
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                cc: ['gcc', 'clang']
        env:
            CC: ${{ matrix.cc }}
        steps:
            - uses: actions/checkout@v4
            - name: Install APT packages
              run: |
                sudo apt update
                sudo apt install \
                    build-essential \
                    graphviz \
                    ${{ matrix.cc }}
            - name: Display versions
              run: |
                ${{ matrix.cc }} --version
                bison --version
                flex --version
            - name: Build dependencies
              run: |
                ./get-deps.sh
                ./get-extra-deps.sh
                ./build-deps.sh
            - name: Enable measurement of coverage
              if: matrix.cc == 'gcc'
              run: |
                echo 'COVERAGE=1' >> "$GITHUB_ENV"
            - name: Build gr1c
              run: |
                make -e all
            - name: Run tests
              run: |
                VERBOSE=1 make -e check
            - name: Report coverage
              if: matrix.cc == 'gcc'
              run: |
                gcov -n $(for k in $(find src exp aux -name \*.c); do basename $k; done) > cov-summary.txt
                echo "### Coverage summary" >> $GITHUB_STEP_SUMMARY
                tail -1 cov-summary.txt >> $GITHUB_STEP_SUMMARY
