---
# configuration for GitHub Actions
name: gr1c tests
on:
    push:
    pull_request:

jobs:
    build-and-test:
        name: Build and test
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                cc: ['gcc', 'clang']
        steps:
            - uses: actions/checkout@v4
            - name: Install APT packages
              run: |
                sudo apt update
                sudo apt install \
                    build-essential \
                    graphviz \
                    ${{ matrix.cc }}
            - name: Display versions
              run: |
                ${{ matrix.cc }} --version
                bison --version
                flex --version
            - name: Build dependencies
              run: |
                ./get-deps.sh
                ./get-extra-deps.sh
                ./build-deps.sh
            - name: Build gr1c
              run: |
                export CC=clang
                make -e all
            - name: Run tests
              run: |
                export CC=clang
                VERBOSE=1 make -e check
